/* rts2root.C
 * Thomas Stroman, University of Utah, 2015-05-28
 * This ROOT script is designed to produce a TTree object from a text
 * file generated by run-stereo-trump.py (or the sample command below).
 * The TTree is named "rts" and written to a file with ".root" replacing
 * ".txt" in the input file name.
 */
#include "TROOT.h"
#include "TTree.h"
#include "TFile.h"

void rts2root(const char* txtfile) {
  
// create a text file using this command:
/*
$TRUMP/bin/rtsparser.run -Etslpcgu y2012m04d11.rts | gawk '$1 != o {print $1,$4,$5*10000+$6*100+$7,3600*$8+60*$9+$10 "." $11,$12,$13,$14,$16,$17,$18,$19,$20,$21,log($22)/log(10.)} {o=$1}' > y2012m04d11.rts.txt
  */
  char format[1024];
  sprintf(format,"n/I:sp:ymd:sec/D:e/F:x:y:u:v:w:x0:lambda:xmax:nmax");

  
  
  TTree *rts = new TTree();
  rts->ReadFile(txtfile,format);
  
  char outfile[1024]; 
  sprintf(outfile,"%s",txtfile);
  sprintf(&outfile[strlen(outfile)-3],"root");
  TFile f(outfile,"RECREATE");
  rts->Write("rts");
  f.Close();
}
